title: WAVE
desciption: >
  Website of the WAVE seismic network Hamburg
email: isleifk@hsu-hh.de
baseurl: "/index" # the subpath of your site, e.g. /blog
#replace nrdybhu1.github.io with your domainname.com
url: "https://kisleif.github.io/WAVEhamburg.github.io/"" # the base hostname & protocol for your site
twitter_username: jekyllrb
markdown: kramdown
page_excerpts: true
favicon: "/img/atlas.png"
collections:
  posts:
    permalink: "/blog/:title:output_ext"
    output: true
defaults:
- scope:
    path: _posts
    type: posts
- scope:
    path: ''
  values:
    image: "/img/preview.png"
plugins:
- jekyll-avatar
- jekyll-feed
- jekyll-redirect-from
- jemoji
- jekyll-paginate

paginate: 5
paginate_path: "/blog/page-:num/"
